// Create a user
POST https://backendpustakacapstone-production.up.railway.app/users
Content-Type: application/json

{
    "name": "user1",
    "email": "user@gmail.com",
    "password": "123456",
    "jenisKelamin": "Perempuan",
    "noTlp": "08123998712",
    "alamat": "Jl jampra lorongs 2 no 12a",    
    "role": "user"
}
###
// get All user
GET https://backendpustakacapstone-production.up.railway.app/users

###
// get Singel user
GET https://backendpustakacapstone-production.up.railway.app/users/9e79a8c9-2358-4c3f-9309-756ac198c5f7

###
// update user
PATCH  https://backendpustakacapstone-production.up.railway.app/users/9e79a8c9-2358-4c3f-9309-756ac198c5f7
Content-Type: application/json

{
    "name": "user Updated",
    "email": "user@gmail.com",
    "password": "",
    "confPassword": "",
    "jenisKelamin": "Perempuan",
    "noTlp": "08123998712",
    "alamat": "Jl jampra lorongs 2 no 12a",    
    "role": "user"
}


###
// delete a user
DELETE   https://backendpustakacapstone-production.up.railway.app/users/47ec9665-c53d-4367-ba17-fa6bb1f5b909

###
// Login User role admin
POST https://backendpustakacapstone-production.up.railway.app/login
Content-Type: application/json

{
    
    "email": "admin@gmail.com",
    "password": "123456"
        
}

###
// Login User role user
POST https://backendpustakacapstone-production.up.railway.app/login
Content-Type: application/json

{
    
    "email": "user@gmail.com",
    "password": "123456"
        
}
###
// Register User role user
POST https://backendpustakacapstone-production.up.railway.app/register
Content-Type: application/json

{
    "name": "user1",
    "email": "user1@gmail.com",
    "confPassword": "123456",
    "password": "123456"
        
}
###
// get Me
GET https://backendpustakacapstone-production.up.railway.app/me

###
// Logout
Delete https://backendpustakacapstone-production.up.railway.app/logout

###
// Created kategori
POST https://backendpustakacapstone-production.up.railway.app/kategori
Content-Type: application/json

{
    "name": "sss"  
}

###
// get All kategori
GET https://backendpustakacapstone-production.up.railway.app/kategoris

###
// get Single kategori
GET https://backendpustakacapstone-production.up.railway.app/kategori/17d142f6-22f3-4d29-b178-94e532c59e5f


###
// Update kategori
PATCH https://backendpustakacapstone-production.up.railway.app/kategori/24369422-6edb-4869-a63f-4a37dd4d72a7
Content-Type: application/json

{
    "name": "Sejarah Indonesia"  
}
###
// delete kategori
DELETE  https://backendpustakacapstone-production.up.railway.app/kategori/458b1d00-0100-42c2-9850-d0acca5dfec0


###
//create book
POST https://backendpustakacapstone-production.up.railway.app/book
Content-Type: application/json

{
    "judul": "Buku asdas",
    "penulis": "Penulis 3",
    "penerbit": "Penerbit 3",
    "cover": "Cover 3",
    "sinopsis": "Sinopsis 3",
    "tahun_terbit": 3003,
    "qty": 3,
    "kategoriId": 3

}

###
// get All books
GET https://backendpustakacapstone-production.up.railway.app/books

###
// get Single books
GET https://backendpustakacapstone-production.up.railway.app/book/b629b56c-b971-47c9-ad1e-3f43087eb708

###
//create book
PATCH  https://backendpustakacapstone-production.up.railway.app/book/704889dc-6300-4ad4-9a36-ec23dcc909a4
Content-Type: application/json

{
    "judul": "Buku 4",
    "penulis": "Penulis 3",
    "penerbit": "Penerbit 3",
    "cover": "Cover 3",
    "sinopsis": "Sinopsis 3",
    "tahun_terbit": 3003,
    "qty": 3,
    "kategoriId": 3

}

###
// Delete book
DELETE https://backendpustakacapstone-production.up.railway.app/book/b629b56c-b971-47c9-ad1e-3f43087eb708

###
// Create Peminjaman
POST https://backendpustakacapstone-production.up.railway.app/peminjaman
Content-Type: application/json

{
    "tanggal_pinjam": "-",
    "tanggal_kembali": "-",
    "status": "Diajukan",
    "userId": 2,
    "bookId": 1
}

###
// Get ALL Peminjaman
GET https://backendpustakacapstone-production.up.railway.app/peminjamans

###
// Get Single Peminjaman
GET https://backendpustakacapstone-production.up.railway.app/peminjaman/7978f8c4-f38c-4aca-abc2-12515eba9bf0

###
// Update Peminjaman
patch https://backendpustakacapstone-production.up.railway.app/peminjaman/2ac27989-6392-4ea8-8187-d87a58e1199a
Content-Type: application/json

{
   
    "tanggal_kembali": "1937-01-01T11:40:27.000Z",
    "status": "Selesai",
    "userId": 2
   
}

###
// Delete Peminjaman
DELETE  https://backendpustakacapstone-production.up.railway.app/peminjaman/2ac27989-6392-4ea8-8187-d87a58e1199a

