// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "user1",
    "email": "user@gmail.com",
    "password": "123456",
    "jenisKelamin": "Perempuan",
    "noTlp": "08123998712",
    "alamat": "Jl jampra lorongs 2 no 12a",    
    "role": "user"
}
###
// get All user
GET http://localhost:5000/users

###
// get Singel user
GET http://localhost:5000/users/9e79a8c9-2358-4c3f-9309-756ac198c5f7

###
// update user
PATCH  http://localhost:5000/users/9e79a8c9-2358-4c3f-9309-756ac198c5f7
Content-Type: application/json

{
    "name": "user Updated",
    "email": "user@gmail.com",
    "password": "",
     "confPassword": "",
    "jenisKelamin": "Perempuan",
    "noTlp": "08123998712",
    "alamat": "Jl jampra lorongs 2 no 12a",    
    "role": "user"
}


###
// delete a user
DELETE   http://localhost:5000/users/47ec9665-c53d-4367-ba17-fa6bb1f5b909

###
// Login User role admin
POST http://localhost:5000/login
Content-Type: application/json

{
    
    "email": "admin@gmail.com",
    "password": "123456"
        
}
###
// Created kategori
POST http://localhost:5000/kategori
Content-Type: application/json

{
    "name": "sss"  
}

###
// get All kategori
GET http://localhost:5000/kategoris

###
// get Single kategori
GET http://localhost:5000/kategori/17d142f6-22f3-4d29-b178-94e532c59e5f


###
// Update kategori
PATCH http://localhost:5000/kategori/24369422-6edb-4869-a63f-4a37dd4d72a7
Content-Type: application/json

{
    "name": "Sejarah Indonesia"  
}
###
// delete kategori
DELETE  http://localhost:5000/kategori/458b1d00-0100-42c2-9850-d0acca5dfec0


###
//create book
POST http://localhost:5000/book
Content-Type: application/json

{
    "judul": "Buku asdas",
    "penulis": "Penulis 3",
    "penerbit": "Penerbit 3",
    "cover": "Cover 3",
    "sinopsis": "Sinopsis 3",
    "tahun_terbit": 3003,
    "qty": 3,
    "kategoriId": 3

}

###
// get All books
GET http://localhost:5000/books

###
// get Single books
GET http://localhost:5000/book/b629b56c-b971-47c9-ad1e-3f43087eb708

###
//create book
PATCH  http://localhost:5000/book/704889dc-6300-4ad4-9a36-ec23dcc909a4
Content-Type: application/json

{
    "judul": "Buku 3",
    "penulis": "Penulis 3",
    "penerbit": "Penerbit 3",
    "cover": "Cover 3",
    "sinopsis": "Sinopsis 3",
    "tahun_terbit": 3003,
    "qty": 3,
    "kategoriId": 3

}

###
// Delete book
DELETE http://localhost:5000/book/b629b56c-b971-47c9-ad1e-3f43087eb708
